spring.application.name=JwtAuth
server.port=8081
spring.data.mongodb.uri=mongodb+srv://yagamistorage2:yagamix1@yagami.d36l7lx.mongodb.net/?retryWrites=true&w=majority&appName=yagami
spring.data.mongodb.database=JwtAuth
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
logging.level.org.springframework.security=DEBUG
